FROM ubuntu:18.04

RUN apt-get update && apt-get install -y git gcc make
RUN apt-get install -y zlib1g-dev libssl1.0-dev

WORKDIR /app

RUN git clone https://github.com/peervpn/peervpn.git
RUN make -C peervpn
RUN find . -ls

RUN apt-get install -y debhelper

RUN apt-get install -y vim

COPY . .
RUN dpkg-buildpackage -rfakeroot
RUN dpkg-deb --build peervpn

