FROM ubuntu:16.04

RUN apt-get update && apt-get install -y git gcc make
RUN apt-get install -y libssl-dev

WORKDIR /app

RUN git clone https://github.com/peervpn/peervpn.git
RUN make -C peervpn

COPY . .
# build debs

RUN find . -ls
